### ISSUE TITLE
Ambiguity with x' A

### ISSUE THREAD

**Issue by matthieugomez** [JuliaMatrices/BandedMatrices.jl#102]
On Julia 1.1
```julia
using BandedMatrices
x = zeros(10)
A = BandedMatrix(Zeros(10, 10), (1, 1))
x'A
ERROR: MethodError: *(::LinearAlgebra.Adjoint{Float64,Array{Float64,1}}, ::BandedMatrix{Float64,Array{Float64,2},Base.OneTo{Int64}}) is ambiguous. Candidates:
  *(A::AbstractArray{T,2} where T, B::BandedMatrices.AbstractBandedMatrix, C...) in BandedMatrices at /Users/Matthieu/.julia/packages/LazyArrays/jsu0l/src/linalg/lazymul.jl:20
  *(x::LinearAlgebra.Adjoint{T,#s623} where #s623<:(AbstractArray{T,1} where T) where T, A::AbstractArray{T,2} where T) in LinearAlgebra at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/matmul.jl:122
Possible fix, define
  *(::LinearAlgebra.Adjoint{T,#s623} where #s623<:(AbstractArray{T,1} where T) where T, ::BandedMatrices.AbstractBandedMatrix)
```

**Comment by dlfivefifty** [comment]
Thanks should be an easy fix (in LazyArrays.jl)

**Comment by matthieugomez** [comment]
Awesome! Thanks again for your package! I use it a lot in my code, and it is a backend for a package I just published on line https://github.com/matthieugomez/InfinitesimalGenerators.jl

**Comment by dlfivefifty** [comment]
Cool package! Glad to hear BandedMatrices.jl was useful.

**Comment by dlfivefifty** [comment]
I was hoping to tag a new version ASAP, unfortunately it looks like METADATA-General sync is down https://discourse.julialang.org/t/switching-package-registration-systems-on-monday/22677/73 so it may take a week or so. In the mean time, master of BandedMatrices.jl and LazyArrays.jl should suffice.
