### ISSUE TITLE
rename bandwidth(A,1),bandwidth(A,2)

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/BandedMatrices.jl#103]
The names `bandwidth(A,1)`, `bandwidth(A,2)` for lower/upper bandwidths are not self-documenting. One option would be `bandwidth(A,:u)` and `bandwidth(A,:l)`.

**Comment by marcusdavidwebb** [comment]
Perhaps also accept :upper and :lower as well as :u and :l for arguments.

**Comment by MikaelSlevinsky** [comment]
Pre-existing Julian code would suggest capital letters (as in `Symmetric(A, :L)`). That would avoid lots of argument parsing code like `if :u, convert symbol to :U`, etc...

Also, if `bandwidth` can be viewed as part of the interface like `size` for an array, then `bandwidth(A,3)` could be relevant for a `BandedTensor`

**Comment by dlfivefifty** [comment]
Ok, your second argument is a good one. let's leave it.
