### ISSUE TITLE
``transpose(vector)*banded_matrix*vector`` returns Array instead of Scalar

### ISSUE THREAD

**Issue by jlbosse** [JuliaMatrices/BandedMatrices.jl#147]
"Sandwiching" a banded matrix with a vector returns an array instead of a vector, whereas Julias Standard Arrays return a scalar in this case. This makes it harder to reuse code that was written with any AbstractMatrix in mind with BandedMatrices. See the following minimal example:

```julia
vector = [1., 0, 0]
matrix = Diagonal([1., 2., 3.])
banded_matrix = BandedMatrix(matrix)

println(transpose(vector)*matrix*vector)
println(transpose(vector)*banded_matrix*vector)
```

which gives

```julia
1.0
[1.0]
```

**Comment by dlfivefifty** [comment]
Hmm it's actually a problem in ArrayLayouts.jl: should be easy to fix, just need a special override for `similar(::MulAdd)`. I think this should be done in a trait-based way so that more types can act like Transpose/Adjoint: e.g., subviews of Transpose.

**Comment by jlbosse** [comment]
For other people reading this: A possible workaround is oing 

```julia
dot(vector, banded_matrix * vector)
```

instead which consistently returns a scalar.

**Comment by jagot** [comment]
I was just thinking about this: is it possible to compute this dot product with a metric, i.e. `dot(x, B, y)` in the Julia 1.3 syntax, where `B` is a banded matrix, allocation-free?

**Comment by dlfivefifty** [comment]
Yes should be as its just a giant sum really. Not sure if it's BLAS already

**Comment by jagot** [comment]
AFAIK there are no contractions in BLAS, except for `dot(x,y)`, so I guess we'd have to roll our own.

**Comment by dlfivefifty** [comment]
This is fixed:
```julia

julia> vector = [1., 0, 0]
3-element Array{Float64,1}:
 1.0
 0.0
 0.0

julia> matrix = Diagonal([1., 2., 3.])
3×3 Diagonal{Float64,Array{Float64,1}}:
 1.0   ⋅    ⋅ 
  ⋅   2.0   ⋅ 
  ⋅    ⋅   3.0

julia> banded_matrix = BandedMatrix(matrix)
3×3 BandedMatrix{Float64,Array{Float64,2},Base.OneTo{Int64}}:
 1.0   ⋅    ⋅ 
  ⋅   2.0   ⋅ 
  ⋅    ⋅   3.0

julia> println(transpose(vector)*matrix*vector)
1.0

julia> println(transpose(vector)*banded_matrix*vector)
1.0
```
