### ISSUE TITLE
Provide a check kwarg to bunchkaufman!

### ISSUE THREAD

**Issue by KristofferC** [JuliaMatrices/BandedMatrices.jl#153]
Tests fail on master (1.4) with

```
LDLᵀ: Error During Test at /home/pkgeval/.julia/packages/BandedMatrices/Jd1re/test/test_symbanded.jl:143
  Test threw exception
  Expression: det(F) ≈ det(SAL)
  MethodError: no method matching bunchkaufman!(::Symmetric{Float32,BandedMatrix{Float32,Array{Float32,2},Base.OneTo{Int64}}}, ::Bool; check=false)
  Closest candidates are:
    bunchkaufman!(!Matched::Hermitian{T,S} where S<:Union{DenseArray{T,2}, ....l; check) at /workspace/srcdir/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/bunchkaufman.jl:109
```

because https://github.com/JuliaLang/julia/commit/018d9aeed6410f2950c66552ffc48f056e402ee3#diff-75e0e85b66a76e7e68009d14f83531b5R570 made Julia call `bunchfaukfman!` with the check keyword argument. Since this package extends the method, it also needs to accept this.

**Comment by dlfivefifty** [comment]
The actual issue is that LinearAlgebra now calls ` _factorize ` instead of ` factorize `. I think this is a bad decision for StdLib, but whatever, I’ve also overloaded ` _factorize `:

https://github.com/JuliaMatrices/BandedMatrices.jl/pull/157
