### ISSUE TITLE
Add support for symmetric banded matrix

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/BandedMatrices.jl#17]
- [x] add new type `SymBandedMatrix{T} <: AbstractBandedMatrix{T}`
- [ ] add conversion routines between `BandedMatrix{T}` and `SymBandedMatrix{T}`
- [x] wrap BLAS routines `ssbmv`
- [x] wrap LAPACK routines `sbtrd` to return a `SymTridiagonal{T}`
- [ ] use BLAS routines for `SubArray{T,<:SymBandedMatrix}`.

**Comment by dlfivefifty** [comment]
@monoke this is relevant for you.

**Comment by MikaelSlevinsky** [comment]
- [ ] add new type `HermBandedMatrix{T} <: AbstractBandedMatrix{T}`
- [ ] add new type `HermTridiagonal{T}`
- [ ] wrap `hbtrd!` to return a `HermTridiagonal{T}`

LAPACK doesn't have specialized eigensolvers for complex symmetric tridiagonal matrices, but this could be done with a complex orthogonal QL algorithm.
- [ ] add eigensolver for `SymTridiagonal{T<:Complex}`
- [ ] add `tridiagonalize!{<:SymBandedMatrix{<:Complex}}`

- [ ] add pure Julian methods for optional `BigFloat` support.

**Comment by dlfivefifty** [comment]
This is no longer relevant as we use `Symmetric{T,BandedMatrix{T}}` and `Hermitian{T,BandedMatrix{T}}`. I'll open up a new issue for `Hermitian{T,BandedMatrix{T}}`.

**Comment by devonwp** [comment]
Is there currently support for Hermitian banded matrices? If not, do you know the easiest way to compute eigenvalues for such matrices?

**Comment by dlfivefifty** [comment]
Yep!
```julia
julia> A = brand(10,10,1,1)
10×10 BandedMatrix{Float64,Array{Float64,2},Base.OneTo{Int64}}:
 0.646715  0.167095   ⋅         ⋅        …   ⋅         ⋅         ⋅ 
 0.479977  0.505987  0.896615   ⋅            ⋅         ⋅         ⋅ 
  ⋅        0.57653   0.335856  0.366855      ⋅         ⋅         ⋅ 
  ⋅         ⋅        0.264954  0.228846      ⋅         ⋅         ⋅ 
  ⋅         ⋅         ⋅        0.744907      ⋅         ⋅         ⋅ 
  ⋅         ⋅         ⋅         ⋅        …   ⋅         ⋅         ⋅ 
  ⋅         ⋅         ⋅         ⋅           0.936787   ⋅         ⋅ 
  ⋅         ⋅         ⋅         ⋅           0.680185  0.102167   ⋅ 
  ⋅         ⋅         ⋅         ⋅           0.584205  0.116184  0.795167
  ⋅         ⋅         ⋅         ⋅            ⋅        0.692564  0.00845409

julia> B = brand(10,10,1,1); B[band(0)] .= 0;

julia> Hermitian(A+im*B) * rand(ComplexF64,10)
10-element Array{Complex{Float64},1}:
  0.21443116802320084 + 0.6363715071310687im
   0.5192332000521915 + 0.049034421125285776im
   0.7728421270377019 + 0.7367163712914542im
  0.41924395120637226 + 0.30281531652696925im
 -0.05620075038518496 + 0.8320093932787733im
  -0.4624028568760076 + 0.8731278433824337im
   1.3947420421655214 + 1.1375478036786524im
   0.6917228643774538 + 1.44827403183141im
  0.11014327566094512 + 0.4670140615554561im
   0.5557332815840778 + 0.24987585300463033im

julia> Hermitian(A+im*B) \ rand(ComplexF64,10)
10-element Array{Complex{Float64},1}:
    1.313066820893483 + 0.3520124071203519im
 0.005637253982829993 + 3.4370568038884564im
  -0.4642943592739055 - 7.871901277303983im
   10.998918838410198 + 14.837596965764464im
   -7.973897242660769 - 8.986544798226975im
     36.2057927404165 - 27.803520025016194im
   -4.308950820937966 + 70.55047435702832im
   -32.25491238906347 - 98.7358222022067im
    92.39337497428141 + 70.63692133759217im
  -11671.144763942106 - 2604.5017807726326im
```

**Comment by dlfivefifty** [comment]
oh, sorry, `eigvals` is not supported. Probably it would be easy to add by modifying https://github.com/JuliaMatrices/BandedMatrices.jl/blob/310699438fd4f2c1089432f96e3f07b5fd47436d/src/symbanded/symbanded.jl#L108 

Assuming there is LAPACK support

**Comment by devonwp** [comment]
I think there is LAPACK support for complex Hermitian banded matrices, but not for complex Hermitian tridiagonal matrices (looking at [this](http://www.icl.utk.edu/~mgates3/docs/lapack.html)). Why is `_tridiagonalize` the place to go to support `eigvals` for complex Hermitian banded matrices (particularly when there appears to be direct LAPACK support for computing eigenvalues of banded matrices)?

**Comment by dlfivefifty** [comment]
Huh, that's a good point: for some reason we tridiagonalize and use `SymTridiagonal`, I don't know why we aren't just calling `sbev!`....

**Comment by devonwp** [comment]
It is possible that LAPACK itself tridiagonalizes to a real symmetric tridiagonal matrix for computing the eigenvalues of both real symmetric and Hermitian banded matrices. Even if this is so though, I imagine it makes more sense to just call the LAPACK driver routines directly. Should I make an issue for this?
