### ISSUE TITLE
Support bandwidths (-1,-1)?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/BandedMatrices.jl#18]
Negative bandwidths are now supported, but _not_ bandwidths that result in no bands.  Should this be supported?

**Comment by gasagna** [comment]
Do you have a use case for no bands? I can't think to any.

**Comment by dlfivefifty** [comment]
Well, it uses 0 memory instead of O(n) memory to represent the corresponding n x n matrix...it also makes the constraints on bandwidths simpler, as there are no constraints instead of the constraint that l + u ≥ 0

**Comment by dlfivefifty** [comment]
I ran into this from a formula for bandwidths that broke down.  I worked around it by taking `max(0,l)` and `max(0,u)`, but in general the contraint `l + u ≥ 0` is harder to enforce.

**Comment by marcusdavidwebb** [comment]
If the code simpler allowing matrices with no bands and all tests still pass with these matrices used, then why not?

Marcus

**Comment by dlfivefifty** [comment]
Ah, because i haven't actually implemented no bands and it make require more checks.
