### ISSUE TITLE
`qr!(A) \ b` is incorrect.

### ISSUE THREAD

**Issue by YingboMa** [JuliaMatrices/BandedMatrices.jl#199]
MWE
```julia
julia> using BandedMatrices, LinearAlgebra

julia> A = brand(5, 5, 3, 3); b = rand(5);

julia> x = qr(A) \ b;

julia> inplace_x = qr!(A) \ b;

julia> x - inplace_x
5-element Array{Float64,1}:
 -3.175391918390031
  1.84667185044204
 -2.3780660555429693
  3.1139376580548332
 -1.8511434079204685
```

**Comment by YingboMa** [comment]
Oops, this is a dup of https://github.com/JuliaMatrices/BandedMatrices.jl/issues/197

**Comment by YingboMa** [comment]
If `qr!` is not supported, maybe it should error instead of giving incorrect answers...

**Comment by dlfivefifty** [comment]
It is supported and in fact used in `qr`, you just need to make sure your bands are padded with zeros.

We could add a check that the top `u` bands are zero.

**Comment by dlfivefifty** [comment]
Closing this since its a dup.
