### ISSUE TITLE
BandedMatrix seems to lose sparsity 

### ISSUE THREAD

**Issue by 00krishna** [JuliaMatrices/BandedMatrices.jl#235]
Hello Folks. 

I noticed some odd behavior, and one of the Julia slack folks suggested I post an issue. I noticed some strange behavior when constructing banded matrices. 

So if I create a banded matrix like the example, I get something like this, which is correct. I can see the dots and all is good.

```
BandedMatrix(-1=> 1:5, 2=>1:3)
6×6 BandedMatrix{Int64} with bandwidths (1, 2):
 0  0  1  ⋅  ⋅  ⋅
 1  0  0  2  ⋅  ⋅
 ⋅  2  0  0  3  ⋅
 ⋅  ⋅  3  0  0  0
 ⋅  ⋅  ⋅  4  0  0
 ⋅  ⋅  ⋅  ⋅  5  0
```

However, when I do this I get what seems to be a dense matrix. And that should not happen, I believe. 

```
BandedMatrix(-2*Eye(4), (4,5))
4×4 BandedMatrix{Float64} with bandwidths (4, 5):
 -2.0   0.0   0.0   0.0
  0.0  -2.0   0.0   0.0
  0.0   0.0  -2.0   0.0
  0.0   0.0   0.0  -2.0
```
So if I wanted to construct a sparse banded matrix, this seems to be incorrect. I am not sure if this is the expected behavior, or if there is a different and better way to create a sparse banded matrix. 
Thanks.

**Comment by oscardssmith** [comment]
Also worth noting that `BandedMatrix(-2*Eye(4))` is correctly sparse.

**Comment by 00krishna** [comment]
Ahh okay, as @contradict on Slack indicated, this is the correct behaviour. Since the matrix bandwidth is too large, it makes all the rows dense. But this is working as expected.
