### ISSUE TITLE
versioned document is not deployed

### ISSUE THREAD

**Issue by hyrodium** [JuliaMatrices/BandedMatrices.jl#249]
https://juliamatrices.github.io/BandedMatrices.jl/v0.16/ returns 404, but https://juliamatrices.github.io/BandedMatrices.jl/dev/ is deployed.

This is because the setting of `DOCUMENTER_KEY` is not correct.
See more information in https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#GitHub-Actions.

![image](https://user-images.githubusercontent.com/7488140/146172021-54e693d2-c274-47cb-b8a2-b5b11be1d2b4.png)

**Comment by jishnub** [comment]
What should be fixed to get this working? The documentation deploy job seems to use the ssh key
https://github.com/JuliaMatrices/BandedMatrices.jl/blob/d82cd4f0cb82341c451506b598151c6286d2ef84/.github/workflows/ci.yml#L64-L66
and the tagbot script as well
https://github.com/JuliaMatrices/BandedMatrices.jl/blob/d82cd4f0cb82341c451506b598151c6286d2ef84/.github/workflows/TagBot.yml#L15-L17
