### ISSUE TITLE
Replace `SymBandedMatrix` with `Symmetric{_,<:BandedMatrix}`

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMatrices/BandedMatrices.jl#34]
Why not just `Symmetric(B::BandedMatrix)`?

It appears that LAPACK methods such as [dsbtrd.f](http://www.netlib.org/lapack/explore-html/d0/d62/dsbtrd_8f_source.html) use two-dimensional indexing on the `data` array (`ab`), so if the LAPACK routines are provided the right integers that describe the sufficient data implied by the symmetry, then the type might not be necessary.

I'm not entirely sure about LAPACK calls, because there are also variables such as `inca` which may not be correct if the data isn't the right size.

**Comment by devonwp** [comment]
By the way, if this was a good idea, do you know why `LinearAlgebra` use `SymTridiagonal` instead of `Symmetric{T,<:Tridiagonal{T}}`?

**Comment by dlfivefifty** [comment]
Because `SymTridiagonal` stores less data than `Symmetric{<:Any,<:Tridiagonal}`. The data stored for `Symmetric{<:Any,<:BandedMatrix}` is precisely the same as for a special type.

**Comment by devonwp** [comment]
> The data stored for `Symmetric{<:Any,<:BandedMatrix}` is precisely the same as for a special type.

Why is this the case? Could you not abandon half the off-diagonal bands in `SymBandedMatrix`?

**Comment by dlfivefifty** [comment]
You can do this already by setting the lower bandwidth to 0
