### ISSUE TITLE
Support C = α*A*B + β*C

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/BandedMatrices.jl#38]
This is supported in `gbmm`. Perhaps we support it as extra cases, for example: 
```julia
# current
banded_matmatmul!(C::BandedMatrix{T}, tA::Char, tB::Char, A::BandedMatrix{T}, B::BandedMatrix{T})
# proposal
banded_matmatmul!(β::Int, C::BandedMatrix{T}, tA::Char, tB::Char, α::T, A::BandedMatrix{T}, B::BandedMatrix{T})
```

@randy3k Any thoughts/objections to this change in your code?

**Comment by randy3k** [comment]
I was following https://github.com/JuliaLang/julia/blob/master/base/linalg/matmul.jl to design the function naming. I personally do not think that covering the extra cases are necessary

1. It is redundant to gbmm!
2. It is not syntactically consistent with julia base.

**Comment by dlfivefifty** [comment]
Hmm, what I actually need needs to work with general matrices: so dispatch to ` gbmm! ` if it’s banded and ` gemm! ` otherwise

**Comment by dlfivefifty** [comment]
I think for now I’ll just put it in BlockBandedMatrices.jl (where I need it)
