### ISSUE TITLE
Hanging precompilation

### ISSUE THREAD

**Issue by haampie** [JuliaMatrices/BandedMatrices.jl#39]
The current version seems to have problems with precompilation:
```julia
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia> Pkg.add("BandedMatrices")
INFO: Installing BandedMatrices v0.3.0
INFO: Package database updated

julia> using BandedMatrices
INFO: Precompiling module BandedMatrices.
^C
signal (15): Ended
while loading /home/.../.julia/v0.6/BandedMatrices/src/BandedMatrices.jl, in expression starting on line 80
```
It just hangs and `Ctrl+C` doesn't stop Julia from using 100% of the CPU.

**Comment by ChrisRackauckas** [comment]
Yes, we followed some precompilation regressions back to here:

https://github.com/JuliaLang/julia/issues/24383
https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/209

**Comment by haampie** [comment]
Oh! Wasn't aware it was reported just a couple hours earlier. Thanks for the references! If it is a regression inside Julia, then this issue can of course be closed @dlfivefifty.

**Comment by dlfivefifty** [comment]
Just comment out `include("precompile.jl")`. (I've already done so on one of my branches I think.)

**Comment by haampie** [comment]
Yeah, I noticed that when I did `Pkg.checkout("BandedMatrices")`. Thanks.

**Comment by ChrisRackauckas** [comment]
This is fixed on master: can it get a tag?

**Comment by dlfivefifty** [comment]
I tagged a release BandedMatrices v0.3.1.

I'm in the process of redesigning the code to not use `StrideMatrix`-like union types, and instead use a trait to indicate whether it's compatible with BLAS routines.

If I find the time, I'll try to put a pull request together for Base that replaces `StridedMatrix` with a trait. Not sure if it'll end up being merged, but at least it will start a conversation.
