### ISSUE TITLE
SymBandedMatrix indexing

### ISSUE THREAD

**Issue by LaurentPlagne** [JuliaMatrices/BandedMatrices.jl#49]
Hi,
I try to use BandedMatrices package and I can’t set values in the symmetric case:

`using BandedMatrices`
`a=BandedMatrix{Float64}(10,1,1)`
`fill!(a,0.0) #OK`
`BandedMatrices.inbands_setindex!(a,12.0,1,2) #OK`
`b=SymBandedMatrix{Float64}(10,1)`
`fill!(b,0.0) #KO indexing not defined`
`BandedMatrices.inbands_setindex!(b,12.0,1,2) #KO indexing not defined`

The documentation does not say much about symmetric matrices so I start to read the implementation but it is not trivial to me…
What would be the correct way to set values in symmetric banded matrices
Thank you for your help.
Laurent

**Comment by dlfivefifty** [comment]
`setindex!` should not work, apart from the diagonal. However, `fill!` should work provided the value is zero.

The error it gives is clearly a bug though.

We may in the future remove `SymBandedMatrix ` in favour of ` Symmetric{<:BandedMatrix} `

**Comment by LaurentPlagne** [comment]
Thank you. So how am I supposed to put values in my symmetric banded matrice ?

**Comment by dlfivefifty** [comment]
Good question. At the moment you have to modify the `data` directly:
```julia
julia> A = SymBandedMatrix{Float64}(Zeros(4,4), 1);

julia> A.data[2,1] = 1; # diagonal

julia> A.data[1,3] = 3; # off-diagonal in 3rd column

julia> A
4×4 SymBandedMatrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  0.0  3.0  0.0
 0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0
```

**Comment by dlfivefifty** [comment]
Let’s leave the issue open as getindex should not throw that error

**Comment by LaurentPlagne** [comment]
Sorry, BTW I don't really understand how the elements are stored...

**Comment by dlfivefifty** [comment]
it’s the same format as ` BandedMatrix ` with bandwidths (0,u) and where the lower triangular entries are defined by symmetry

**Comment by dlfivefifty** [comment]
I'm closing this as `SymBandedMatrix` has been removed (in favour of `Symmetric{T,BandedMatrix{T}}`.
