### ISSUE TITLE
Cannot create a variable of the type SymBandedMatrix

### ISSUE THREAD

**Issue by danieljschmidt** [JuliaMatrices/BandedMatrices.jl#61]
Both
``SymBandedMatrix{Float64}(Zeros(4,4), 1)``
and 
``sbrand(10,2)``
yield the following error:
``MethodError: no method matching BandedMatrices.SymBandedMatrix{Float64}(::Compat.UndefInitializer, ::Array{Float64,2}, ::Int64)``

**Comment by dlfivefifty** [comment]
What version? It works for me:
```julia
julia> SymBandedMatrix{Float64}(Zeros(4,4), 1)
4×4 BandedMatrices.SymBandedMatrix{Float64}:
 0.0  0.0   ⋅    ⋅
 0.0  0.0  0.0   ⋅
  ⋅   0.0  0.0  0.0
  ⋅    ⋅   0.0  0.0
```

**Comment by danieljschmidt** [comment]
Thank you for the answer! I have just found out that the problem only occurs when I work within a Jupyter notebook; it does not appear in "plain" Julia (for whatever reason). So I assume that the error is unrelated with the BandedMatrices package.
