### ISSUE TITLE
Constructor with pairs and size no longer works

### ISSUE THREAD

**Issue by clason** [JuliaMatrices/BandedMatrices.jl#65]
The following constructor from the `Readme.md` no longer works:
```julia
BandedMatrix((-1=> 1:5, 2=>1:3), (n,m),(l,u))
```
(even after inserting the missing comma). 

What is now the easiest way of constructing a banded matrix with given size *and* (constant) bands such as the classical finite difference stencil for the Laplacian? (Something like 
```julia
BandedMatrix((-1=>1.0, 0=>-4.0, 1=>1.0), (n,n))
``` 
would be ideal...)

**Comment by dlfivefifty** [comment]
Sorry, I’ll fix that now. The easiest is
```Julia
A = BandedMatrix{Float64}(undef, (n,n), (1,1))
A[band(0)] .= -2/h^2
A[band(1)] .= A[band(-1)] .= 1/h^2
```
See also

https://github.com/JuliaMatrices/BandedMatrices.jl/blob/master/examples/clarrays.jl

**Comment by dlfivefifty** [comment]
Yes I should add a finite difference example. If you make one I’d be happy to accept a PR.

Note that OpenBLAS (Julia’s default) is pretty slow for banded matrices. If you use MKL (JuliaPro) or Apples BLAS it’s much faster.

**Comment by dlfivefifty** [comment]
Note you can also use ` SymTridiagonal ` in Base.

**Comment by clason** [comment]
I was using the following snippet:
```julia
using BandedMatrices, SparseArrays, BenchmarkTools
n = 10000
h = 1/n
A = BandedMatrix{Float64}(undef, (n,n), (1,1))
A[band(0)] .= -2/h^2
A[band(1)] .= A[band(-1)] .= 1/h^2
B = sparse(A)
C = SymTridiagonal(A)
f = fill(1.0,n)
```
Then
```
julia> @btime $A\$f;
  643.493 μs (7 allocations: 469.03 KiB)

julia> @btime $B\$f;
  2.662 ms (64 allocations: 5.42 MiB)

julia> @btime $B\$f;
  173.811 μs (8 allocations: 234.66 KiB)
```

(I'm on Linux and have weened myself off MKL since they changed their free license to prohibit academic work -- not sure if bundling with JuliaPro changes that. But good to know! In any case, things become more interesting with 2D operators using `kron` and with `BlockBandedMatrices` for optimality systems for PDE-constrained optimization.)

**Comment by dlfivefifty** [comment]
The README constructor now works.
