### ISSUE TITLE
Banded Jacobian

### ISSUE THREAD

**Issue by matthieugomez** [JuliaMatrices/BandedMatrices.jl#86]
I solve non linear PDEs of the form 0 = f(V, ∂xV ,∂xxV) using finite-difference schemes. I usually use `NLsolve` as non linear solver.  

Critically, the Jacobian of the system is a banded matrix. I would love a way for `DiffEqDiffTools` to know that, so that it only needs to compute the relevant derivatives (and also stores the jacobian in an efficient form). Basically what I'd like is a special `DiffEqDiffTools.finite_difference_jacobian!` signature for `BandedMatrix` (not sure where it should live, so also @ChrisRackauckas).

**Comment by dlfivefifty** [comment]
Sounds great! But this issue probably belongs in the DiffEq changing of things.
